"""Write cookies to a file in Netscape HTTP Cookie File format."""

from __future__ import annotations

from datetime import datetime, timezone
from pathlib import Path

from .reader import Cookie

_HEADER = (
    "# Netscape HTTP Cookie File\n"
    "# https://curl.se/docs/http-cookies.html\n"
    "# This file was generated by fcookex.\n"
    "\n"
)


def _to_netscape_line(cookie: Cookie) -> str:
    include_subdomains = "TRUE" if cookie.host.startswith(".") else "FALSE"
    is_secure = "TRUE" if cookie.is_secure else "FALSE"
    return (
        f"{cookie.host}\t{include_subdomains}\t{cookie.path}\t"
        f"{is_secure}\t{cookie.expires}\t{cookie.name}\t{cookie.value}\n"
    )


def export(
    cookies: list[Cookie],
    output_dir: Path,
    output_name: str | None = None,
    append: bool = False,
) -> Path:
    """Export *cookies* to a Netscape-format file inside *output_dir*.

    Args:
        cookies: Cookies to write (real values, not masked).
        output_dir: Directory in which to create the file (created if absent).
        output_name: Bare filename without directory component. A ``.txt``
            suffix is added automatically when absent.  Defaults to
            ``cookies_<ISO8601>.txt``.
        append: When *True*, append to an existing file instead of
            overwriting.  The Netscape header is omitted if the file
            already has content.

    Returns:
        The path of the written file.
    """
    output_dir.mkdir(parents=True, exist_ok=True)

    if output_name is None:
        ts = datetime.now(tz=timezone.utc).strftime("%Y%m%dT%H%M%SZ")
        filename = f"cookies_{ts}.txt"
    else:
        filename = output_name if output_name.endswith(".txt") else output_name + ".txt"

    out_path = output_dir / filename

    # Decide whether the header is needed *before* opening the file for writing.
    needs_header = not append or not out_path.exists() or out_path.stat().st_size == 0

    mode = "a" if append else "w"
    with open(out_path, mode, encoding="utf-8") as fh:
        if needs_header:
            fh.write(_HEADER)
        for cookie in cookies:
            fh.write(_to_netscape_line(cookie))

    return out_path
